name: firebase_simplify
description: A command-line tool for simplifying Firebase integration and management.
version: 1.1.0
homepage: https://github.com/Darkbeast-glitch/EasyFirebase.git
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  io: ^1.0.4
  process_run: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
